#!/usr/bin/env python
import rospy
from hippocampus_common.node import Node
from mavros_msgs.srv import SetMode
from mavros_msgs.msg import State


class AutoOffboardNode(Node):
    """Checks the vehicle's mode and sets it to 'OFFBOARD' if it is not in this
    mode already.

    """
    def __init__(self, name, anonymous=False, disable_signals=False):
        super(AutoOffboardNode, self).__init__(name,
                                               anonymous=anonymous,
                                               disable_signals=disable_signals)

        self.state_sub = rospy.Subscriber("mavros/state",
                                          State,
                                          self.on_state,
                                          queue_size=1)
        self.set_offboard = rospy.ServiceProxy("mavros/set_mode", SetMode)

    def on_state(self, msg: State):
        if msg.mode != "OFFBOARD":
            try:
                self.set_offboard(custom_mode="OFFBOARD")
            except rospy.ServiceException:
                rospy.logerr("Failed to set offboard mode.")
            rospy.sleep(1.0)


def main():
    node = AutoOffboardNode("auto_offboard")
    node.run()


if __name__ == "__main__":
    main()
