#!/usr/bin/env python
import rospy
from hippocampus_common.node import Node
from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped, \
    Vector3Stamped
from mavros_msgs.msg import AttitudeTarget
import tf.transformations


class QuatToRpyNode(Node):
    def __init__(self, name):
        """Subscribes to a message containing a quaternion and converts
        the orientation from quaternion to roll-pitch-yaw angles and publishes
        it in a Vector3Stamped message under the `rpy` topic.

        Supported message types are: PoseStamped, PoseWithCovariance,
            AttitudeTarget.

        Args:
            name (str): Name of the node. Must be unique.
        """
        super(QuatToRpyNode, self).__init__(name=name)
        self.msg_type = self.get_param("~msg_type")
        self.pub = rospy.Publisher("rpy", Vector3Stamped, queue_size=10)
        if self.msg_type == "PoseStamped":
            self.sub = rospy.Subscriber("orientation",
                                        PoseStamped,
                                        self.on_orientation,
                                        queue_size=10)
        elif self.msg_type == "PoseWithCovarianceStamped":
            self.sub = rospy.Subscriber("orientation",
                                        PoseWithCovarianceStamped,
                                        self.on_orientation,
                                        queue_size=10)
        elif self.msg_type == "AttitudeTarget":
            self.sub = rospy.Subscriber("orientation",
                                        AttitudeTarget,
                                        self.on_orientation,
                                        queue_size=10)
        else:
            rospy.logerr("[%s] Pose msg type defined does not exist.",
                         rospy.get_name())

    def on_orientation(self, msg):
        rpy = Vector3Stamped()
        rpy.header.stamp = msg.header.stamp
        rpy.header.frame_id = msg.header.frame_id

        if self.msg_type == "PoseStamped":
            q_ros = msg.pose.orientation
        elif self.msg_type == "PoseWithCovarianceStamped":
            q_ros = msg.pose.pose.orientation
        elif self.msg_type == "AttitudeTarget":
            q_ros = msg.orientation

        q = [q_ros.x, q_ros.y, q_ros.z, q_ros.w]
        euler = tf.transformations.euler_from_quaternion(q)
        rpy.vector.x = euler[0]
        rpy.vector.y = euler[1]
        rpy.vector.z = euler[2]
        self.pub.publish(rpy)


def main():
    node = QuatToRpyNode("quat_to_rpy")
    node.run()


if __name__ == "__main__":
    main()
