#!/usr/bin/env python

import rospy
from sensor_msgs.msg import FluidPressure
from hippocampus_common.node import Node
from hippocampus_common import ms5803


class BaroNode(Node):
    def __init__(self):
        super(BaroNode, self).__init__("water_baro_node")

        i2c_address = self.get_param("~i2c_address", 0x76)
        self.barometer = ms5803.MS5803(i2c_address)

        self.baro_publisher = rospy.Publisher("baro",
                                              FluidPressure,
                                              queue_size=1)

    def run(self):
        rate = rospy.Rate(hz=50)
        while not rospy.is_shutdown():
            pressure, temperature = self.barometer.get_measurement()
            msg = FluidPressure()
            msg.header.stamp = rospy.Time.now()
            msg.fluid_pressure = pressure
            self.baro_publisher.publish(msg)
            rate.sleep()


def main():
    node = BaroNode()
    node.run()


if __name__ == "__main__":
    main()
