# Default sensor poses for HippoCampus

# Frame convention following ROS/Gazebo
sensor_poses:
  vertical_camera:
    x: 0.13
    y: 0.0
    z: -0.03
    roll: 0.0
    pitch: 1.57
    yaw: 0.0
  barometer:
    x: 0
    y: 0
    z: -0.05
