name: YAPF Formatting Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run YAPF to test if python code is correctly formatted
        uses: AlexanderMelde/yapf-action@master
        with:
          args: --verbose
